---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

rust:
  root: /opt
  path: /opt/cargo

near:
  validator:
    source_url: https://github.com/near/nearcore
  cli:
    general:
      source_url: https://github.com/near/near-cli-rs/releases/download
    validator:
      source_url: https://github.com/near-cli-rs/near-validator-cli-rs/releases/download
    ports:
      p2p_port: 24567
      rpc_port: 3030
      metrics_port: 3031
